modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="siongsngs_fantasy_world"
version="1.0.0"
displayName="Siong Sng's fantasy World"
credits="@2021 By Siong Sng"
displayURL="https://discord.gg/5w9BUM4"
authors="Siong Sng(Barry23412)"
description='''
This is a multi-world mod developed by Siong Siong, hoping that everyone can play more diverse Minecraft through this mod
'''

[[dependencies.siongsngs_fantasy_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




