modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="siongsngs_fantasy_world"
version="1.0.0"
displayName="Siong Sng's fantasy World-菘菘的幻想世界"
credits="@2021 By Siong Sng"
displayURL="https://discord.gg/5w9BUM4"
authors="菘菘(Barry23412)"
description='''
這是一個由菘菘所開發的多世界模組，旨在希望大家能夠透過該模組玩到更多的樣性的Minecraft
'''

[[dependencies.siongsngs_fantasy_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




